blank_issues_enabled: true
contact_links:
    - name: ğŸ’¡ Propose Ideas
      url: https://github.com/pinely-international/proton/discussions/new?category=ideas
      about: 
    - name: ğŸ¤” Questions and Help
      url: https://github.com/pinely-international/proton/discussions/new?category=q-a
      about: 
   - name: ğŸˆâ€â¬› Join Discord
      url: https://discord.gg/sHp2pxrSws
      about: 
